### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by mujohn26** [hakoemmy/hakoemmy#1]
Hey emmy what does this PR does ? what is it's purpose at all ?

**Comment by hakoemmy** [comment]
@mujohn26

Thank you for reaching out!

 A couple of days ago Github has released a cool feature.

I am taking advantage of it.

**Comment by hakoemmy** [comment]
Here is a blog post that explains the thing like so: [go visit it](https://dev.to/natterstefan/how-to-add-a-readme-to-your-github-profile-2bo9)
